
function initMacros(){//Defintion of Macros, CONSTANTS PUBLICS
	#macro ITEM_DEF_NAME 0
	#macro ITEM_DEF_DESCRIPTION 1
	#macro ITEM_DEF_SPRITE 2
	#macro ITEM_DEF_ACTION 3
	#macro ITEM_DEF_MAX 4
	
	#macro ITEM_POTION 0
	#macro ITEM_KEY 1
	#macro ITEM_MURAL 2
	#macro ITEM_STRINGS 3
	#macro ITEM_GUITAR 4
	#macro ITEM_SPADE 5
	#macro ITEM_SMALLKEY 6
	#macro ITEM_STYLUS 7
	#macro ITEM_BLOWTORCH 8
	#macro ITEM_FISH 9
	#macro ITEM_COFFEEBEANS 10
	#macro ITEM_WINCONDITIONCOFFEE 11

	
	#macro INVENTORY_ITEM 0
	#macro INVENTORY_QUANTITY 1
	
	#macro STATE_IDLE 0
	#macro STATE_READING 1
}